server:
  port: 3006
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  cloud:
    gateway:
      routes:
        - id: UBERAUTHPROJECT
          uri: lb://UBERAUTHPROJECT
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3
          order: 0

        - id: UBERFILEPROJECT
          uri: lb://UBERAUTHPROJECT
          predicates:
            - Path=/api/v1/driver/**
          filters:
            - StripPrefix=2
          order: 0

        - id: UBERBOOKINGSERVICE
          uri: lb://UBERBOOKINGSERVICE
          predicates:
            - Path=/api/v1/booking/**
          filters:
            - StripPrefix=3
          order: 0

        - id: UBERLOCATIONSERVICE
          uri: lb://UBERLOCATIONSERVICE
          predicates:
            - Path=/api/v1/location/**
          filters:
            - StripPrefix=3
          order: 0

        - id: UBERREVIEWSERVICE
          uri: lb://UBERREVIEWSERVICE
          predicates:
            - Path=/api/v1/review/**
          filters:
            - StripPrefix=3
          order: 0

        - id: HD-FARESERVICE
          uri: lb://HD-FARESERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
          order: 100
eureka:
  client:
    service-url:
      defaultZone: http://hd-eureka-server:8761/eureka/


jwt:
  expiry: 86400000
  secret: mrstmmusicfasdfasdfasdfasdfasfdasdf

cookie:
  expiry: 86400000
