server:
  port: 3006
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  application:
    name: HeavyDriver-ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: UBERAUTHPROJECT
              uri: lb://UBERAUTHPROJECT
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: UBERBOOKINGSERVICE
              uri: lb://UBERBOOKINGSERVICE
              predicates:
                - Path=/booking/**
              filters:
                - StripPrefix=1

            - id: UBERLOCATIONSERVICE
              uri: lb://UBERLOCATIONSERVICE
              predicates:
                - Path=/location/**
              filters:
                - StripPrefix=1

            - id: UBERREVIEWSERVICE
              uri: lb://UBERREVIEWSERVICE
              predicates:
                - Path=/review/**
              filters:
                - StripPrefix=1



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
